### ISSUE TITLE
Interested in getting involved

### ISSUE THREAD

**Issue by jondo2010** [OpenSimulationInterface/open-simulation-interface#103]
Hi All,

I wasn't sure who I should contact, so I'm creating a quick "issue" here.

I'm representing AID (aid-driving.eu) which is an Audi concern located in Munich. I'm very interested in using OSI in our simulation infrastructure, and would like to also contribute back whatever I can.

Is there a mailing list you are using? Regular meetings?

Cheers,
John

**Comment by CarloVanDriestenBMW** [comment]
Hi John,
that does definitly qualify as a issue  👍 
There is no official mailinglist or regular meetings by a group of "special people" :) We sometimes use the Pegasus events in order to discuss issues and possible solutions which in the end are further worked on in Github with Pull-Requests or Issues. It would be interesting for us to learn more about your usage and your requirements in order to check if the current state of OSI is suitable for you.
There will be a major update on 26th of January which might be interesting for you to look at! Just keep track of the upcomming pull-requests.
Best regards
Carlo

PS: @AndreasKernAudi might be an interesting contact for you!

**Comment by AndreasKernAudi** [comment]
Hi John,

OSI is developed here on Github. No more infomationen needed. ;-)

At Audi we do not using OSI in our projects yet. We have an own standard "FEP VU". The focus is more "ground truth" oriented. And we have libraries to process the data, including OpenDRIVE.

I hope you know the details. If not please contact Ludwig Friedmann or me via Email!

Our mid-term goal is to bring "FEP VU", OSI and similar formats together. In my opinion this will be the next big step in the standardization of simulation after of OpenDRIVE (+OpenCRG) and OpenSCENARIO. 

I will close this ticket. I think your original questions are answered.

Best regards,
Andreas
