### ISSUE TITLE
Standardized way of sending OSI data 

### ISSUE THREAD

**Issue by jr7** [OpenSimulationInterface/open-simulation-interface#227]
Is there a defined standard for sending OSI messages ?
For example, in a streaming protocol, how is the message size defined?
One approach would be to use  length-prefix framing.

Also how to define which type of message is send on a certain channel ?
Or is there only one type of osi message ? (like a wrapper msg around all other osi messages)

**Comment by CarloVanDriestenBMW** [comment]
Hi Jonas,
there are some "best practices" on how the packaging for OSI works. There is already a  [NetworkProy](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/tree/master/examples/OSMPCNetworkProxy). The idea is in generell to seperate the architecture/packaging and middleware from each other. The Network Proxy will be upgraded soon for 3.0 :)

**Comment by pmai** [comment]
Standards for communicating OSI data are set as layered standards, so that appropriate mechanisms can be chosen for different use cases. One of these is the OSI Sensor Model Packaging standard (OSMP), see the neighboring repo https://github.com/OpenSimulationInterface/osi-sensor-model-packaging , which specifies how to wrap a model into an FMU and transport the OSI messages via pointers (for FMI 2.0 via integer variables, for FMI 2.1 this will be the directly supported binary type).

For simple socket communication, one can use length-prefix framing as you say (see the demo code OSMPCNetworkProxy in the OSMP repo for a simple example of this). Other users are sending OSI proto buffers also directly as payloads of such mechanisms as 0mq, or ROS messages, where the length of the payload is already communicated.

An example of a more complex protocol is the RFMI protocol that we designed as a flexible protocol to support remote access to FMUs, including those having an OSMP-compliant interface (see https://pmsf.eu/resources/fmi/RFMI.html for details).

**Comment by jr7** [comment]
Hi, 
Regarding  the NetworkProxy  example, in this line : 

```
if (ensure_tcp_proxy_connection(component)) {
            int recv_buffer_size=0;
            char* recv_buffer_ptr=NULL;
            int recvval=0;
            recvval=recv(component->tcp_proxy_socket,(char*)&(recv_buffer_size),sizeof(recv_buffer_size),MSG_WAITALL);
```
as far as I understand this is using an integer for the message prefix.
So  right now this approach is not considering i.e. the endianess on a certain architecture 
also the definition of  Integer itself may vary on different systems/compilers
Have you discussed this so far? 

Regarding the OSI-Sensor-Modell-Packaging.
In this case the only type of message which is used for communication,
would be the OsiSensorData I suppose? 
Have you also considered an approach where the type of  osi_msg would be prefixed to the
header ? 

Thank you for your feedback, BR  Jonas Ruebsam

**Comment by pmai** [comment]
The code in the OSMPCNetworkProxy example is provided for simplicity, not as a production ready replacement for proper middleware. In the cases where its currently used endiannness is not a problem (intel&arm won ;). Dito for int-size issues (Alpha died ;). The old wars are over...

OSI Sensor Model Packaging covers `osi::SensorData` for the 2.2.0 release of OSI, since that was the only message type exchanged for sensor models. For OSI 3.0.0 (see master branch of OSMP), it covers `osi3::SensorView` and `osi3::SensorData` as both inputs and outputs, with `osi3::SensorViewConfiguration` for parametrization. Other message types can also be communicated (using the annotations), but there is currently no requirement for those message types to be supported by e.g. environment simulations.

The question really is, what do you intend to do with OSI, and with whom do you intend to communicate, which would govern which kind of middleware to use. Spinning your own middleware is always possible, though I'd only recommend doing so, if you have specific needs that are not covered by out of the box solutions. That's one of the reasons why OSI itself does not talk about the communication part, since that is left to the middleware employed by design.

**Comment by carsten-kuebler** [comment]
OSI has defined top-level messages, which are send and received from models. Other messages aren't send/received.

**Comment by jr7** [comment]
Ok, Thank you for your feedback!
