### ISSUE TITLE
Value safety / Type safety in OSI

### ISSUE THREAD

**Issue by mbencik999** [OpenSimulationInterface/open-simulation-interface#238]
Recently I had encountered an unpleasant situation. The size of a sign in the TrafficSign class can be set to a negative value. Now since it is pointless to make an custom type that is unsigned double or something similar, the question arose how to handle issues in OSI where is obvious that the values should not be negative or something else. Is there a plan to make OSI safe in that way?
The next issue is that OSI allows to copy from any type to an class. This is especially troublesome with CopyFrom function which allows to copy from any type to any type. This is not an error at compile time but it creates undesired behavior in runtime. This is difficult to debug and could be avoided if the CopyFrom function would only have full specialization.

**Comment by pmai** [comment]
There is no data type in ProtoBuf (or, for that matter in most IDLs) that allows you to specify only non-negative floating point numbers (most IDLs are more concerned with data portability than data specification). And for other relevant invariants nearly no IDL has the expressive power to describe these (again IDLs do not generally have very expressive type systems when compared with statically typed functional languages, for example).

So there will remain a large number of invariants that can only be expressed in the specification as natural language and can only be checked by additional code.

The issues of CopyFrom and type safety are unrelated to OSI, since these are implementation artefacts of the ProtoBuf => programming language mapping being employed, and could be fixed there, if wanted, without impact on the IDL or the OSI spec.

**Comment by LudwigFriedmannBMW** [comment]
After no further questions have been asked I close the issue.
