### ISSUE TITLE
global_ground_truth in sensor view

### ISSUE THREAD

**Issue by haoyuanying** [OpenSimulationInterface/open-simulation-interface#246]
The definition of global_ground_truth defined in sensor_view actually behalves as "sensor releated ground truth", since it got filterd by sensor FoV, which defined in sensorviewconfiguration. IMHO, this is incorrect to be named as "global_ground_truth", should be named as "sensor_ground_truth". Also, this configuration does not help sensor models, since the objects that are placed outside the sensor FoV may interfere the sensor detections, eg. raytracing with Multi-Path effects. @CarloVanDriestenBMW What do you think?

**Comment by pmai** [comment]
FWIW the thing is named global_ground_truth because everything is still in global coordinates, and the filtering is only a performance optimization: It is in essence still the global ground truth, just not all of it, necessarily (i.e. partial_ground_truth might be more useful as a name).

Sensor models must configure their sensor view in such a way, that they get all relevant objects, i.e. if the sensor model wants to model the effect of objects outside its official FoV, the FoV in sensorviewconfig must be made larger than the technical FoV: The FoV in sensorviewconfig is used for filtering the global ground truth for performance reasons (and to simplify the model task somewhat by eldiing obviously irrelevant data), not as a 1:1 mapping of the technical FoV of the actual sensor.

Hence the current definition is really intended for the sensor model. Maybe documentation needs to be strengthened to finally get this point across.

**Comment by haoyuanying** [comment]
IMHO, the FoV configuration should map to the technical FoV of the real sensor, otherwise it creates a big confuse. I would then suggest to change the FoV related names in sensorviewconfiguration to "[prefix]_field_of_view_xxx", it can differ from the technical FoV parameters clearly. 

There is another point of this issue, since the sensorviewconfiguration supposes to bring the function to send the sensor configuration (eg. FoV) at the initialization phase, and the sensor models should be configured on the fly accordingly. However, if the FoV is modelled larger than the real FoV to include the effects that I mentioned in last comments, the sensor model is eventually configured in a incorrect manner. The real FoV still has to be hard coded in the models. 

Therefore, I suggest to include / introduce another FoV in sensorviewconfiguration to 1:1 map the real technical FoV.

**Comment by pmai** [comment]
@mbencik999 to the contrary the design does support exactly this example: A sensor model for long-range radar would specify a sensorviewconfig FoV of 360 deg and a range that encompasses all relevant objects based on the maximum useful signal range in air (e.g. 1-2km). In this way the sensor will get a full ground truth cookie around its location, without the need to send all ground truth (which could encompass objects 100s of km away for long running scenarios).

Again the FoV specified by the sensor model in sensorviewconfig is the specification for filtering the ground truth, it is not in any way shape or form bound to what one would find in a datasheet (those values BTW are rarely related to actual performance anyway ;).

**Comment by pmai** [comment]
@haoyuanying This is another misunderstanding: SensorViewConfiguration is a mechanism for the sensor model to request certain input (i.e. the SensorView) from the simulation environment, i.e. it is used to configure the simulation environment on the fly, not the other way around. If it was intended as a mechanism to configure the model (which it is not), it would be called SensorModelConfiguration or SensorConfiguration.

There is currently no standardised way to configure a generic sensor model, since each generic sensor model will have different parameters, with different effects, depending on the sensor model internals. Users and Environments are free to use FMU parameters to implement such generic models, and based on those other parameters the sensor model will then request an appropriate SensorView through its SensorViewConfiguration.

There is also no need for the technical sensor FoV to be specified anywhere in the simulation environment <-> sensor model OSI interfaces since only the sensor model needs to know about those; all FoV information exchanged through SVC and SV is intended to configure output of the simulation environment to the sensor model, whereas the actual FoV is something the sensor model implements (and can e.g. dynamically change BTW).

**Comment by pmai** [comment]
I definitely agree that we need to improve the documentation on this point, especially I think we need a complete architectural introduction in the documentation (something along the lines of some of the stuff in #98 but cleaned up and updated to the stuff that we actually released).

**Comment by LudwigFriedmannBMW** [comment]
Hello @pmai and @CarloVanDriestenBMW, as a first step, how about adding a very simple signal diagram to the wiki, e.g.
![osi_gt_sv_sd](https://user-images.githubusercontent.com/40625995/44273043-a71a7080-a23e-11e8-8a11-c73a3f3b4843.png)

Based on this simplistic illustration, more complex concepts like SensorViewConfiguration can be explained.

**Comment by pmai** [comment]
Looks good to me!
