### ISSUE TITLE
Traffic value sign member name expression

### ISSUE THREAD

**Issue by mbencik999** [OpenSimulationInterface/open-simulation-interface#248]
The question is there is the member field value_unit in the TrafficSignValue in my view this should be measurement_unit. Because we want to express measurement types.

**Comment by pmai** [comment]
I don't understand this issue: The value_unit is the unit of the value that is printed on the additional sign, which is IMHO unrelated to any measurement (besides the fact that all sensor readings are interpreted measurements). I.e. it is not a unit of measurement.

**Comment by mbencik999** [comment]
Unfortunately it is not strictly speaking. A unit value is 1 of something. A measurement value is a unit of measurement is a definite magnitude of a quantity( km/h, mp/h, kg etc.. ). For that formal definitions exist.

**Comment by pmai** [comment]
Maybe I am still confused, but the field is called value_unit because it is the unit of the value field of the sign, not because it is a unit value. So maybe a more explicit name would have been value_measurement_unit, but in common usage (as per Oxford https://en.oxforddictionaries.com/definition/unit and Merriam-Webster https://www.merriam-webster.com/dictionary/unit ) unit is commonly understood to encompass physical measurement units.

In any case changing field names requires more or less a major release of OSI, so this is something that can only be cleaned up, if needed, in OSI 4.0...

**Comment by mbencik999** [comment]
Ok I see the confusion now. The confusion that I have is simple. A unit value describes basicaliy 1. For example eigen vector or a value in any random system. But we chose the SI system, so agreed to a common measurement system.  So the vector from before has a unit value 1 but in our SI system it can be 23 cm or something else. That is why we need a more expressive name. Measurement_unit or SI_unit.

**Comment by LudwigFriedmannBMW** [comment]
I think it is relatively clear that in the context of a traffic sign value_unit is not a unit vector or a unit length. Morevover, value_unit also uses the explicitly specified type _Unit_. I do not think that an extension of the documentation is necessary here. If no further objections come up to 10.08. I will close the issue.

**Comment by LudwigFriedmannBMW** [comment]
After no further questions have been asked I close the issue.
