### ISSUE TITLE
convert-to-proto3

### ISSUE THREAD

**Issue by kmeids** [OpenSimulationInterface/open-simulation-interface#257]
I recently compiled  the latest open-simulation-interface release with the proto3 syntax, the "convert-to-proto3.sh" works like a charm, though in the current proto2 files their are no "required " fields or "[default = xx] values assigned adding the following script update could handle them if they do exist:

mv $f $f.pb2 && sed -e 's/syntax *= *"proto2";/syntax = "proto3";/' -e 's/^\([ \t]*\)optional /\1/' -e 's/^\([ \t]*\)required /\1/' -e 's/ \[default\(.*\)/\;/g' $f.pb2 > $f

Best regards,
Kmeid Saad

**Comment by pmai** [comment]
Hi, thanks for the suggestion, however there is a reason the script intentionally does not do this, since removing defaults or required attributes would change the meaning of the proto file (and thus also the valid on-the-wire protocol) silently, and is thus dangerous. For those reasons use of required and default values are prohibited in OSI for now, and the proto3 compilation would fail safely in those cases.

We should be more explicit on this in the documentation and CI tests, so I'll keep this issue as a reminder for improving CI testing.

**Comment by LudwigFriedmannBMW** [comment]
For this kind of topics, we probably set up something like a developer documentation. As this is short notice for OSI 3.0.1, I will postpone this issue.
