### ISSUE TITLE
OSI v2.x.x: Daimler change requests

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#3]
@SoykaDaimler 
You should review the version 17 and adjust the implementation in an extra branch accoring to the Daimler specifications. We will discuss the changes and present them to the @OpenSimulationInterface/change-control-board-ccb

**Comment by SoykaDaimler** [comment]
@CarloVanDriestenBMW 
Hi Carlo,
what kind of workflow are we using, e.g. how do I get my suggestions on the server? I could not create a branch on the remote repository. I guess only admins have write access. I cloned the repo and made my adjustments locally. Are we using a forking workflow? https://www.atlassian.com/git/tutorials/comparing-workflows#forking-workflow
Then I could create a pull request. I have some changes which need discussing and revising. So a workflow where we can work on a shared branch together would be good.

**Comment by mbinna** [comment]
@CarloVanDriestenBMW Is it possible to change the access rights so that other major contributors can create remote branches to work on new features? If not, the workflow suggested by @SoykaDaimler might be used.

@SoykaDaimler If you don't want to maintain your own fork, there is usually no need to fork the origin repository to work on a new feature and perform a code review. A new feature branch in this repository is sufficient. You can then create a new pull request within the repository to start a discussion about the feature you implemented. This simple workflow is called [GitHub Flow](https://guides.github.com/introduction/flow/).

**Comment by CarloVanDriestenBMW** [comment]
Thanks @mbinna 
I changed the access rights of the @OpenSimulationInterface/pegasus-developer to "write". Now everyone can create a branch. The workflow is described at the wiki page

**Comment by CarloVanDriestenBMW** [comment]
@SoykaDaimler I read your comment about a OSI workshop and I personally think that is definitly necessary! We should discuss this with @raueATconti .
