### ISSUE TITLE
Lane boundary discretization and sensor field of view

### ISSUE THREAD

**Issue by TimFrickeBMW** [OpenSimulationInterface/open-simulation-interface#318]
Strictly speaking, OSI does not define how lane boundaries are to be discretized. It does so only for centerlines. But let's assume that the same definition applies for lane boundaries.

Imagine a lane boundary that is straight for a long distance. According to OSI definition, few points are needed here for discretization:

> When the points are pairwise linearly connected,
        // the lateral distance to the real ideal line (as used by the
        // simulation environment internally) must not exceed 5cm.

So, let's say that the points defining the lane boundary in GroundTruth are 10 meters apart.

Now imagine a sensor with a very narrow field of view: it only "sees" along one meter of the lane boundary. It thus only perceives one or even none of the GroundTruth points.

Would this be a problem? Or will a sensor model have to generate additional points along the lane boundary that lie within the sensor field of view to provide meaningful SensorData? Generally, how should lane boundaries be discretized - in GroundTruth and SensorData?

**Comment by LudwigFriedmannBMW** [comment]
Hi Tim,
as already written in #319, a discretization in the order of the sensor resolution is required for the use-case you're describing.
Transmitting the geometry of multi-lane roads with such high resolutions via network interfaces is not very performant.
Rather, a corresponding refinement of the discretization should be implement in the (sensor specific) user code.

**Comment by pmai** [comment]
I think the rule for SensorData is fairly simple: The data output will depend on what the real sensor would output in that situation: Might be the whole lane is not output at all, because the sensor has too narrow a field of view and can’t reliably detect the marking. Or the marking is output with very coarse discretisation and few points. Or highly reliable, because sensor is high-res, fine discretisation ...

For the ground truth the rule is that the simulator must output everything that is covered by the given field of view, but can output more (the field of view for the sensor view is just informational to allow the simulator to reduce obviously unneeded data). Hence I’d say that at least two points need to be given so that the slope of the marking is reliably transmitted. If that means one or both of the points are widely out of the field of view that is OK.

**Comment by LudwigFriedmannBMW** [comment]
Hi @TimFrickeBMW, 
does that answer your question? Or would you make a proposal for the extension of the documentation?

**Comment by TimFrickeBMW** [comment]
My question has been answered and I think there is no need for further documentation (apart from what I suggested in #319 )
