### ISSUE TITLE
GroundTruth outside the SensorView field of view

### ISSUE THREAD

**Issue by TimFrickeBMW** [OpenSimulationInterface/open-simulation-interface#319]
A SensorView defines a certain field of view. It contains GroundTruth. Is it acceptable to include information in this GroundTruth that is outside this field of view?

If the lane boundaries exist in a discretized form (point clouds) and the SensorView field of view is small enough - or the distance between points large enough - it is possible that only one point of a lane boundary is included in SensorView-->GroundTruth. This is practically useless. Therefore, I would suggest in this case that for each lane boundary, the first point that is not anymore inside the field of view is transmitted anyway. This leads to the above question.

Also see #318. I think OSI needs to specify lane boundary discretization in more detail.

**Comment by LudwigFriedmannBMW** [comment]
Hi @TimFrickeBMW,
in my opinion, the margin which you want to add to the field of view, is sensor specific.
A generalized extension of the field of view could lead to a situation in which the sensor recognizes more than it actually can.
Therefore, I'd like to discuss whether the extension of the SensorView you're proposing shouldn't be implemented in the user code.

**Comment by pmai** [comment]
The simulator is allowed to include data in the ground truth that is outside the requested field of view, and as discussed in #318, sometimes it must.

Generally speaking it is the responsibility of the sensor to specify a field of view that is large enough to properly model its sensor, hence the given field of view will usually be larger than the field of view of the sensor from its data sheet, e.g. to model deviations in the corners of the field of view.

OTOH it is the responsibility of the simulator to faithfully represent the ground truth in that requested field of view. And a very simple simulator can just output the whole ground truth all of the time, since the requested field of view for the ground truth is just an efficiency filter, not a naive sensor model.

**Comment by LudwigFriedmannBMW** [comment]
Hi @TimFrickeBMW, 
does that answer your question? Or would you make a proposal for the extension of the documentation?

**Comment by TimFrickeBMW** [comment]
I would suggest rephrasing the following definition:

https://github.com/OpenSimulationInterface/open-simulation-interface/blob/a8fb7ccebe22c14662a86b5649077785ed5adeb3/osi_sensorview.proto#L105-L108

Suggested new definition:
```
    // This is the ground truth that is provided to the sensor model by the
    // simulation environment. It may be filtered as per the requirements of the
    // sensor model as expressed by the \c SensorViewConfiguration message(s)
    // that are exchanged during the simulation initialization phase.
```
