### ISSUE TITLE
Usage of left/right versus free lane boundaries

### ISSUE THREAD

**Issue by TimFrickeBMW** [OpenSimulationInterface/open-simulation-interface#320]
In osi3::Lane::Classification, the IDs of left lane boundaries, right lane boundaries and free lane boundaries can be given.

Is it a valid approach to identify the boundaries **of all lanes** as "free" and **never** detail which boundary is left or right? Or why do the messages `left_lane_boundary_id` and `right_lane_boundary_id` even exist?

**Comment by CarloVanDriestenBMW** [comment]
@ppannusch is there a reason to do so in the simulation or might it be useful for the sensor or function developer?

**Comment by ppannusch** [comment]
Free lane boundaries where only created for junctions, where a distinction between left and right per sé is not possible / useful.
Any normal lane would only use left/right lane boundaries.
And this information is very helpful for the simulator **and** sensor models; e.g. for intelligent traffic models that can more easily (and less computationally heavy) localize themselves, or a camera that actually outputs left and right lane boundaries.

**Comment by TimFrickeBMW** [comment]
Of course it is useful. However, you cannot always identify lane boundaries as left or right - even in the case of roads outside junctions.
Imagine a small dead-end road. You enter it, follow until the end, turn around, and drive back. Which side is left, which is right?
Therefore, identifying lane boundaries as left or right should in my opinion be optional. The simulator should be allowed to specify all lane boundaries as "free". Moreover, I would argue that the association with left and right is an interpretation of the ground truth and should therefore not be present in OSI::GroundTruth.

**Comment by pmai** [comment]
Isn't the dead-end example more a case of the limitations of lane modeling, and not lane boundaries: If the dead-end is currently modeled as a single lane, then traffic would not be able to turn around. For that to work you either need two (potentially overlapping) lanes, or you need to model that as a junction, which does not have lanes, hence the lane boundaries are all free.

I.e. this problem is rather a problem of the lane model itself, not of left/right lane boundaries...

**Comment by pmai** [comment]
Or in other words, lanes are already an interpretation of ground truth, but a rather practically useful one, since doing away with lanes (and potentially even roads), will lead to all traffic participant models having to provide full-blown lane/road-detection logic.

**Comment by mbencik** [comment]
There is a more tricky problem and that is lane change. If a street has two lanes in one direction, the car can change lanes. Lets say the car is first in the left lane and changes position to the right lane. With that change the lane boundaries definition changes automatically. The before right lane boundary becomes a left boundary, and a new right boundary has to be set for that vehicle.  

The problem here is that this left / right lane boundary stuff is dependent on the driving direction and has to be set separately for each vehicle. This would really create a definition problem for the lane boundaries. 

To each lane one would need to assign the lane boundary IDs and define on the ground of the driving direction which one is left which is right.

**Comment by pmai** [comment]
The lane boundaries are defined separately exactly for that reason, so that adjacent lanes (and also opposing lanes, including overlapping lanes for small roads that allow travel in both directions ) will reference the boundaries as left/right as it fits, so I don’t see any problems there.

Again, ignoring for the moment that all definitions of roads and lanes are illusory, the boundaries do not add anything more complex to the picture.

**Comment by ppannusch** [comment]
I agree that there are no problems in left/right definition.
It is defined per lane, and, more importantly, has nothing to do with any vehicle's travel direction. It can be properly defined according to the lane's driving direction, which is implicitly defined by the center line (which is either with or against driving direction of the lane).
If a vehicle travels against the driving direction of a lane, the left boundaries simply become right boundaries in "vehicle space", and the right boundaries can be recognized as left boundaries.
Only driving backwards is a little more complicated, but that is also well definable and nothing the simulator needs to bother with.

**Comment by CarloVanDriestenBMW** [comment]
> 
> 
> Of course it is useful. However, you cannot always identify lane boundaries as left or right - even in the case of roads outside junctions.
> Imagine a small dead-end road. You enter it, follow until the end, turn around, and drive back. Which side is left, which is right?
> Therefore, identifying lane boundaries as left or right should in my opinion be optional. The simulator should be allowed to specify all lane boundaries as "free". Moreover, I would argue that the association with left and right is an interpretation of the ground truth and should therefore not be present in OSI::GroundTruth.

Have a look at #156 where we have already identified the problem with dead-ends.
