### ISSUE TITLE
Bundling KPIs rules

### ISSUE THREAD

**Issue by ainar** [OpenSimulationInterface/open-simulation-interface#332]
For now, the OSI validation software https://github.com/OpenSimulationInterface/osi-validation requires that the rules are written into YAML files. To reduce the maintenance needs of the OSI toolchain, the idea is to implement the rules directly into the OSI .proto files, into the comments. I made a prototype of what it could be, by using the Doxygen parsing and filtering capabilities.

For my prototype, the rules still follows a YAML like syntax and are described here: https://ainar.github.io/osi-validation/rules.html

I implemented for testing purposes two rules for the field _atmospheric_pressure_ of the _EnvironmentalConditions_ message type.

How it does look in the .proto files:

```
    // Atmospheric pressure in Pascal at z=0.0 in world frame (about 101325
    // [Pa]).
    //
    // Unit: [Pa]
    //
    // \rules
    // is_set
    // in_range: [800e+2, 1200e+2]
    // \endrules
    //
    optional double atmospheric_pressure = 3;
```

How it does look on the HTML compiled Doxygen documentation:

![image](https://user-images.githubusercontent.com/12114853/59519145-84410300-8ec7-11e9-91dc-4ab8c717ffbc.png)

_Note: 800e+2 means 80000. To avoid confusion, I am currently changing all values in decimal notation (with written zeros)._

These imply a modification of the model for Doxygen parameters file _doxygen_config.cmake.in_. Then the parsing for validation purposes is handled in the validation software, thanks to the generation of a XML version of the documentation.

This – I think – major update of OSI would need to review and add all the KPIs rules into the .proto files. It would be done only once, but then the maintenance needs are limited.

Please tell me if you have any remark or question.

**Comment by CarloVanDriestenBMW** [comment]
Does "is_set" actually mean "mandatroy"? It just defines if a field has to be set and if the rule does not set this property the checker does not care if the field is available or not?

**Comment by CarloVanDriestenBMW** [comment]
It would be great to have examples for each defined rule in the documentation.

**Comment by CarloVanDriestenBMW** [comment]
Is it correct that Doxygen detects errors in the rules automatically while building if e.g. a defined rule is not available or misspelled?

**Comment by mbencik** [comment]
"is_set" actually means to check if a field is set. But it is slightly confusing to what it should correspond.

**Comment by ainar** [comment]
> Does "is_set" actually mean "mandatroy"? It just defines if a field has to be set and if the rule does not set this property the checker does not care if the field is available or not?

`is_set` is a rule that check if the Protobuf Field is well defined ; the validation software actually do this thanks to the Protobuf's `HasField()` method that check if the field is set. ([see protobuf documentation for `HasField` method](https://developers.google.com/protocol-buffers/docs/reference/python-generated#singular-fields-proto3))

> It would be great to have examples for each defined rule in the documentation.

That is a good idea. I will do that soon.

> Is it correct that Doxygen detects errors in the rules automatically while building if e.g. a defined rule is not available or misspelled?

It is not... Nothing new is happening during Doxygen bundling ; there is no preliminary syntax checking. The mispelled rules are only detected during the validation process. In fact, there is no modification of Doxygen runtime to implement these *bundled rules*. I just added [aliases](http://www.doxygen.nl/manual/config.html#cfg_aliases) for the tags `\rules` and `\endrules`.

**Comment by CarloVanDriestenBMW** [comment]
Are there any fields which are not checked for "is_set"? I would assume that every mandatory field is checked for this rule, which are all except the ones explicitly marked "optionally" in the documention?

I the defintition and naming of the set of rules should correspond to the properties of describing the "quality" and "compliance" with the standard:

- A field must is mandatory or optional. Mandatory is the default which results in a rule "is_optional". Therefore the validator suit does check all fields if they are set and throws an "error" if a mandory is not set and possibly a "warning" if an optional field is not set?
- A field needs to be in a certian range. Rule: "is_in_range", "is_range", "has_range" ... the validator will throw an error if the field has a value out of that range.
- A field has a certain "fulcrum" like "at Z=0.0 the value must be 101325 [Pa]"

So the rules are from a wording point of view not describing "what the validator is doing" but more "The requirements towards the specific field in terms of standard compliance"


PS: I really like the work here:

- We have parser clearly defining the rules in one place
- We are using a Doxygen feature for this
- The rules are used for the documentation and for the validation suite
- The rules are part of the documentation
- There is only one place to change the specific values for a rule and thats the standard interface itself
- The rule definition should be part of the osi repository because they are "part of the standard"

**Comment by CarloVanDriestenBMW** [comment]
> It is not... Nothing new is happening during Doxygen bundling ; there is no preliminary syntax checking. The mispelled rules are only detected during the validation process. In fact, there is no modification of Doxygen runtime to implement these bundled rules. I just added aliases for the tags \rules and \endrules.

In this case we would have to define the build checker rules in python as it is currently done in 

> test_cases_doc.py

**Comment by CarloVanDriestenBMW** [comment]
@pmai I would be interested in your opinion on that! I would suggest to proceed in this way.

**Comment by pmai** [comment]
I generally like the overall idea, so would be in favour of moving in this direction. I also definitely like the work going on in terms of building up the validator (sadly too little time to be actively involved in that for now).

We have to be careful about semantics in the validation itself though: ProtoBuf does not distinguish between a field being not filled out, and a field having the default value: E.g. for a field like speed, with default value of 0, the field will not be encoded on the wire if the vehicle does have speed 0, even if the sender explicitly set that value. So in terms of validation it will be tricky to do, without also specifying what the sender has to be doing (i.e. specifying a scenario, where speed is ensured to be some actual value).

Also currently all fields in OSI are actually non-mandatory (with very few implicit exceptions). And in the future, as discussed in #325, we may need to tailor the set of active fields for performance reasons. So it would be valid for a sender not to fill out some/all of the fields.

So I think the devil will be in defining suitable validation criteria. But the overall approach is definitely something we should be persuing. So a PR to add the necessary machinery for this seems the way to go, and later on we can add/change the set of validation rules.

I'd also start with domain rules, since they add important information in some cases.

**Comment by CarloVanDriestenBMW** [comment]
@pmai the non-mandatroy part is actually not true (see readme.md)

> Additionally, this is the default behavior in protobuf version 3 that does no longer have the required type and therefore ensures update compatibility. However, this does not mean that filling the field is optional. For the purpose of providing a complete interface, all existing fields should be set, unless not setting a field carries a specific meaning as indicated in the accompanying comment.

**Comment by jdsika** [comment]
This has been completed by #375
