### ISSUE TITLE
Clarification of other places for EnvironmentalConditions

### ISSUE THREAD

**Issue by goretkin** [OpenSimulationInterface/open-simulation-interface#337]
Currently, there are `UNKNOWN` levels of different environmental conditions, e.g.

```
        // Intensity of precipitation is unknown (must not be used in ground
        // truth).
        //
PRECIPITATION_UNKNOWN = 0;
``` 

in 
https://github.com/OpenSimulationInterface/open-simulation-interface/blob/f9b13826c360b4a492b3a84d4dd55b2d5566d85d/osi_environment.proto#L82 ,

which is not to be used in ground truth. Is there another place in which `message EnvironmentalConditions` appears outside of the ground truth message?

**Comment by jdsika** [comment]
This is actually due to the fact that the enums of all messages are structured like that. You are in fact correct that the message is currently not used by SensorData but in theory could be by a "rain sensor". We concluded some time ago that is a rule that there are no "unknown" values in a simulation environment because it provides the "ground truth" -> Gods view on earth :)

The comment _(must not be used in ground truth)_ could be left away in this case. I am in favor of keeping the same enum style everywhere instead of removing the "unknown" value?

**Comment by jdsika** [comment]
@vkresch let's fix this by improving the comment!
