### ISSUE TITLE
Material Properties & Model References

### ISSUE THREAD

**Issue by kmeids** [OpenSimulationInterface/open-simulation-interface#403]
#### Open Questions:
Extended material properties for different objects inside the virtual environment are necessary to better support stochastic and physics based sensor models. Though a field "model_reference" is currently provided for stationary and moving objects, it is still lacking for other objects available inside the simulation environment e.g. traffic signs, lane marking etc.

1. How to handle material properties for objects that are not defined as StationaryObject or MovingObject? 
2. Should the "model_reference" field point out to a standardized file format, if yes is it the ".gltf" and the openMaterial initiative by @LudwigFriedmann?
3. Would a predefined 3D geometry and material properties file format influence the OpenX Harmonization initiative, @HendrikAmelunxen?

#### Note:
This issue is a result of the Sensor Modeling Working Group meeting that took place on 07.30.2020.

**Comment by raue** [comment]
wrt. 1.: what are these objects, which belong neither to stationary nor to moving object classes? I only could think of preciptitation, which would mean water w/ different states of aggregarion.

**Comment by LudwigFriedmann** [comment]
Hi @kmeids ,
I'd like to answer the questions as follows:

Since version 3.1, OSI provides _map_reference_ in the groundtruth message and_model_reference_ in the object message as opaque references to 3D models. While the former may be used to reference static road network/infrastructure, buildings and environment, the latter can reference static/dynamic objects that do not have to be aligned with the map. Complemented by object positions and orientations,  _map_reference_  and _model_reference_s enable creation and update of dynamic scene graphs in rendering and physical sensor simulation. Environmental effects defined in osi_environment can complement the individual simulation needs.

Even though ASAM OpenDRIVE and ASAM OpenSCENARIO also include opaque references to 3D models, a corresponding file format was not yet specified. In my opinion, the selection of an appropriate format is the fundamental first step on the way to achieve interoperability and consistency in driving simulation, rendering and physical sensor simulation. It strongly influences further discussions on model structure and material annotation.

With [OpenMaterial](https://github.com/LudwigFriedmann/OpenMaterial), I tried to set up a starting point for these discussions. Within the exploration phase of this project, I identified [Khronos glTF](https://github.com/KhronosGroup/glTF) as an open, extendable candidate to form the basis for the file format. As a first proof of concept, I created an extension proposal with a first set of material parameters annotated via mesh or texture references to corresponding 3D models.

As mentioned above, OpenMaterial can be a starting point for further discussions on file format, material definition and annotation, model structure, etc. I'd be happy if we could enter into a more in-depth discussion there. In the medium term, I hope that a group of interested parties will form that will elaborate results of these discussions within a self-contained standardization project.

**Comment by kmeids** [comment]
> wrt. 1.: what are these objects, which belong neither to stationary nor to moving object classes? I only could think of preciptitation, which would mean water w/ different states of aggregarion.

Other non OSI stationary or moving object classes may refer to TrafficSign, TrafficLight, LaneBoundary, RoadMarking etc..

**Comment by kmeids** [comment]
> Hi @kmeids ,
> I'd like to answer the questions as follows:
> 
> Since version 3.1, OSI provides _map_reference_ in the groundtruth message and _model_reference_ in the object message as opaque references to 3D models. While the former may be used to reference static road network/infrastructure, buildings and environment, the latter can reference static/dynamic objects that do not have to be aligned with the map. Complemented by object positions and orientations, _map_reference_ and _model_reference_ (s) enable creation and update of dynamic scene graphs in rendering and physical sensor simulation. Environmental effects defined in osi_environment can complement the individual simulation needs.
> 
> Even though ASAM OpenDRIVE and ASAM OpenSCENARIO include opaque references to 3D models, too, a corresponding file format was not yet specified. In my opinion, the selection of an appropriate format is the fundamental first step on the way to achieve interoperability and consistency in driving simulation, rendering and physical sensor simulation. It strongly influences further discussions on model structure and material annotation.
> 
> With [OpenMaterial](https://github.com/LudwigFriedmann/OpenMaterial), I set up a starting point to address these topics. Within the exploration phase of this project, I identified [Khronos glTF](https://github.com/KhronosGroup/glTF) as an open, extendable candidate to form the basis for the file format. As a proof of concept, I created an extension proposal with a first set of material parameters annotated to corresponding 3D models.
> 
> As mentioned above, OpenMaterial can be a starting point for further discussions on file format, material definition and annotation, model structure, etc. I'd be happy if we could enter into a more in-depth discussion there. In the medium term, I hope that a group of interested parties will form that will elaborate results of these discussions within a self-contained standardization project.

Hello @LudwigFriedmann 
Thanks for the reply, _map_reference_ and _model_reference_ are a great start and for the time being they both more or less complement physics based sensor simulation approaches.

For OpenMaterial, and the idea of having a standardized file format, I will definitely put this point for discussion in our next big meeting round. **Meanwhile, I invite every non-ASAM member to directly comment on this topic here on github.**

**Comment by kmeids** [comment]
Current work-flow would be through the model_reference filed, closing this issue.
