### ISSUE TITLE
Compare: OSI and DIN70000

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#51]
As mentioned in #42 there may be discrepancies between these two sources. We should talk about this in the Workshop.

**Comment by CarloVanDriestenBMW** [comment]
Question: Is the bounding box dynamic?

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW The ISO8855 and DIN 70.000 define the same vehicle coord. system and to "our disappointment" it is yaw->roll->pitch. (See Tabelle 1 Seite 16 in ISO8855). Should we change the definition in OSI? It will affect all orientations, spherical coords (issue #148) and maybe the polygons (issue #154 define polygon clockwise instead of counter-clockwise).
OSI uses the american definition of vehicle coord. systems (See https://en.wikipedia.org/wiki/Axes_conventions#/media/File:RPY_angles_of_cars.png).
OSI uses few more angles in messages, which could be defined similar (OSI::Reflections in OSI::SensorView...

**Comment by martin-fzd** [comment]
I don't see any resons **not** to stick to the refered ISO / DIN norms in an interface standardization initative like this. Any other opinions?

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler I would like the complete OSI to be checked for definitions which are not compatible with ISO8855 and all of them reworked. Please check the complete document if possible. I guess it has only 45 pages so it is ok :)

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW There is no need to change our lane or road definitions?!

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler Your proposal is good! Maybe we consider #14 ? I already asked @pmai for an opinion there.

We will check the lane definitions - could you talk with T. Schaller?

**Comment by TimFrickeBMW** [comment]
For the record: there is no "american way of rotation". The Wikipedia article (!) cited does indeed state "roll-pitch-yaw", but **as a name, not as a definition.** What may be confusing is that extrinsic rotations around x-y-z (roll-pitch-yaw) result in the same attitude as intrinsic rotations around z-y'-x'' (yaw-pitch-roll). From my experience, the common definition around the world is the Tait-Bryan convention of intrinsic rotations z-y’-x″, whis is often incorrectly referred to as "Euler angles". Note that in the Wikipedia article cited above there is even a link to the "Tait-Bryan angles".

**Comment by carsten-kuebler** [comment]
Another standard which is used in america is SAE J670. The standard SAE J670's z-axis definition points to the bottom.

**Comment by TimFrickeBMW** [comment]
Z pointing downwards is very common in the aerospace domain. In a North-East-Down system, a vehicle's yaw angle corresponds to the compass heading -- 0° for (True) North, 90° for East, etc. I think it makes sense to stick with z pointing upwards here, because it is more intuitive for relative positions. In the rare cases where an object's compass heading is required, it can be obtained from the East-North-Up yaw angle via a simple transformation.
