### ISSUE TITLE
libopen_simulation_interface(_pic) as shared lib?

### ISSUE THREAD

**Issue by AndreasVIRES** [OpenSimulationInterface/open-simulation-interface#55]
The osi lib as a static library leads to errors (http://stackoverflow.com/questions/33017985/static-linking-with-generated-protobufs-causes-abort), because we have to link it into every sensor and into the tool.

A shared lib seems reasonable.

**Comment by pmai** [comment]
For uses that are coordinated (e.g. sensor model and tool come from same source), I think going the shared library route is realistic and the better idea in any case, I'll add this as a build target (in fact I'd suggest this to be the default library name, changing the current non-PIC static library name to `_static` in the process so that users have to specify it to do static linking).

Most sensor FMUs will however likely use their own private static library copy, since linking shared libraries through pre-linking is quite accident prone for FMUs, and using C++ shared libraries by on-demand loading is not practical. However there should not be any conflicts, since only encoded buffers are exchanged between tool and sensor model and no C++ objects cross the line (see discussion in stackoverflow link above, also this is what we have been seing in testing multiple sensor FMUs in one process).

**Comment by pmai** [comment]
Can you test whether this build change fixes your issues?

**Comment by AndreasVIRES** [comment]
Thanks, it works now.

**Comment by CarloVanDriestenBMW** [comment]
I will review the change now and close the issue with the pullrequest

**Comment by AndreasVIRES** [comment]
Ah ok, sorry.

**Comment by PhilippRoethigBMW** [comment]
After the changes it would not build for me with default settings in Release Mode. I had to change the Runtime Library from Multithreaded-DLL (/Md) to Multithreaded-Debug-DLL (/MDd). But now it's partly Debug and not completely in Release Mode anymore. Is there another way to solve this problem? @pmai

**Comment by pmai** [comment]
Hmmm, Release builds work for me without manual changes, i.e. just using /Md. Are you certain that CMake finds a protobuf library that was compiled with release settings? I've only seen this kind of error when some part of the project was compiled with debug settings...

**Comment by PhilippRoethigBMW** [comment]
This was the problem. Now it was working. Thanks for your help!
