### ISSUE TITLE
Problems with dynamic linking

### ISSUE THREAD

**Issue by clemenshabedank** [OpenSimulationInterface/open-simulation-interface#592]
#### Describe the feature
The OSI library must offer the possibility that within a C++ program (one process) two or more different OSI versions can be used simultaneously as dynamic libraries (shared libraries).
This is not possible due to the "Custom Options" [1] in the current OSI version 3.X.X with the used FileOption (see [2]).
and leads to the following runtime error:

```
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/extension_set.cc:93] Multiple extension registrations for type "google.protobuf.FileOptions", field number 81000.
unknown file: Failure
C++ exception with description "Multiple extension registrations for type "google.protobuf.FileOptions", field number 81000." thrown in the test body.
```

[1] https://developers.google.com/protocol-buffers/docs/proto#customoptions
[2] https://github.com/OpenSimulationInterface/open-simulation-interface/blob/6ae62d627fc10f40b6cb567989b94caab6502751/osi_version.proto.in#L54

**Important note:** As discussed a reminder for the v4.0 release (not backward compatible). This issue is uploaded by me on behalf of BMW. 

@pmai @ThomasNaderBMW FYI

**Comment by ReinhardBiegelIntech** [comment]
We at [openPASS](https://gitlab.eclipse.org/eclipse/simopenpass/simopenpass) are also interested in having this problem solved :-)

Is there a fix planned for v4.0.0 or is it still in discussion?

**Comment by ReinhardBiegelIntech** [comment]
I did some tests and found the "Multiple extension registrations" error to disappear, if I just don't access the extension.
So if I don't use [this code](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/fb5da5e5462e129eae40f48e4ae3bd6fbb228fed/osi_version.proto.in#L19) (or use it only once in the process), the usage of multiple libraries seems to be fine.

**Comment by ThomasNaderBMW** [comment]
Feedback from my colleague Markus Schönbeck (sry it is German):
-	Wenn man nicht den Sourcecode aller Komponenten unter Kontrolle hat, kann es dennoch zu diesem Problem kommen, wir haben keine Garantie, dass dies nicht benutzt wird.
-	Letztendlich sollte dieser Fehler vollständig ausgeschlossen werden (wie von OpenPath anscheinend ja auch gewünscht).
-	Etwas, was vorhanden ist, nicht zu benutzen,  weil es sonst zu Problemen kommt, ist ein Design-Fehler ((selbst wenn der Workaround bei OpenPath zu funktionieren scheint).

**Comment by ReinhardBiegelIntech** [comment]
Related: https://github.com/protocolbuffers/protobuf/issues/6029

**Comment by PhRosenberger** [comment]
Related: https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/issues/87

**Comment by pmai** [comment]
Since this came up in discussions again todyay, the way to avoid problems with multiple registrations on Linux, while still allowing multiple versions of OSI to coexist is to link all users statically against both protobuf and OSI libraries, **and** to use the `-Bsymbolic` linker flag (`-Wl,-Bsymbolic` on the  gcc command line) when generating the shared objects (i.e. the FMUs), which prevents global ELF symbol interposition from the executable into the shared object.

The problem occurs when an executable (i.e. the simulator) includes a copy of protobuf and OSI, and FMUs (i.e. shared objects) are loaded into the simulator without proper isolation flags being used in the ldopen call; then global symbol references in the shared object are first looked up against the executable image, and only if not found there are looked up in the shared object. This is called ELF symbol interposition, which allows an executable to interpose common definitions of plugins, but which wreaks havoc in our case.

The alternative on Linux is to link everything dynamically (i.e. shared) against the exact same version of protobuf and OSI shared libraries, which then works out, but is against the whole idea of FMI and OSI in that everything depends on exactly identical versions/binaries and is not independent anymore.

On Windows the problem does not occur, here static linking everything just works, because there is no ELF symbol interposition (and actually only specially marked symbols, not all global symbols, partake in DLL dynamic linking, which can present its own problems, but is of no concern in our use cases).

**Comment by ClemensLinnhoff** [comment]
Thank you for the explanation @pmai!
How would you set the linker flag when using `cmake ..` and `cmake --build .`?
I tried setting `set(CMAKE_STATIC_LINKER_FLAGS "-Wl,-Bsymbolic")` and alternatively `set_target_properties(OSMPDummySource PROPERTIES PREFIX "" LINK_FLAGS "Wl,-Bsymbolic")` in the CMakeLists in both OSMPDummySource and OSMPDummySensor. But the error `File already exists in database: osi_version.proto` still occurs during co-simulation with OpenMCx.

**Comment by pmai** [comment]
For cmake 3.13 and higher, the portable way to add the flags would be either

```
add_link_options("LINKER:-Bsymbolic")
```

at project level or 

```
target_link_options(OSMPDummySensor PRIVATE "LINKER:-Bsymbolic")
```

at target level (prior to 3.13 you'd use add_libraries/target_link_libraries).

This ensures that the proper way to pass the linker flags to the linker is used for each compiler, i.e. `-Wl` is only for gcc, clang uses `-Xlinker`.

You also have to ensure that everything is statically linked, including protobuf itself.

**Comment by pmai** [comment]
Just to expand on the latter point:

> You also have to ensure that everything is statically linked, including protobuf itself.

This usually requires your own custom build of protobuf, as you need a static library that has itself been built with -fPIC (i.e. as DSO-ready position-independent code), which is needed (depending on many circumstances, so just generalizing here) to link it into a shared object. Usually either no static library exists, or if it exists it has been built for inclusion into an executable, where -fPIC is not needed.

**Comment by ClemensLinnhoff** [comment]
Thank you very much for your last comment, @pmai. That's it!
I had do get protobuf and build it from source with running `./configure --disable-shared CXXFLAGS="-fPIC"` before running `make`.
So in detail:
Download protobuf, unzip and go to the extracted folder. Then run the following commands:
```
./configure --disable-shared CXXFLAGS="-fPIC"
make
sudo make install
sudo ldconfig
```

I did not have to change anything in the CMakeLists, so `-Bsymbolic` did not have to be set.

**Comment by ClemensLinnhoff** [comment]
> That smells like a PR for the doc improvements?

It does! We will verify this on a second system and then create a PR.

**Comment by jruebsam** [comment]
Hi, 
since it has been requested here is my short summary how I do linking on Windows / Linux

### Windows

#### Dynamic Linking

Since, on windows symbols are not exported per default it can be kind of annoying to deal with this during 
protobuf header generation (see for example  https://groups.google.com/g/protobuf/c/PDR1bqRazts).
So basically thats one reason to use static linking.

#### Static Linking 

Static linking requires to manually build protobuf. 
Its important to notice that on windows you can also specify how to link against the C runtime (not sure how this works on linux).  
Basically this can be set in CMake e.g. https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html


So when statically linking it makes sense to still dynamically link against the C Runtime.
(This is important e.g. when building shared libraries, since a static C runtime will create an isolated heap for your  dll,
which can lead to segfaults depending on what you expose on your public interfaces)


The easiest way to achieve this on Windows without setting all the stuff manually in Cmake and building protobuf 
is to actually use vcpkg:

#### Install static protobuf: 
 vcpkg install --triplet=x64-windows-static-md protobuf

This vcpkg triplet enables static linking with dynamic c-runtime.

#### Build: 

For cmake configuration we can directly specify our vcpkg installation:

`cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows-static-md  -DCMAKE_TOOLCHAIN_FILE=C:/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -A x64 `

`cmake --build . --config Release`

### Linux

There is already a good answer from pmai so here some additional points to this.

#### Dynamic linking 

As already mentioned by pmai shared linking is an option on linux.
`LINK_WITH_SHARED_OSI` has to be enabled.

#### Static linking 

A common error here is to just install protobuf with apt and link against it. 
This means that your OSI is build statically but still linking dynamically against protobuf.
Here, again either protobuf has to build statically from source or some solution e.g. vcpkg needs to be utilized.

**Comment by PhRosenberger** [comment]
Tank you very much @jruebsam for your well written summary!

**Comment by PhRosenberger** [comment]
In the meantime, I could verify that you only need to build your protobuf from source and configure it with `./configure --disable-shared CXXFLAGS="-fPIC"` to get your co-simulation running.

I will now start a docu PR that should close all realted issues.

**Comment by PhRosenberger** [comment]
Let's continue the discussion for the [README PR](https://github.com/OpenSimulationInterface/open-simulation-interface/pull/715) and the [Docu PR](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/pull/93).
