### ISSUE TITLE
ISO23150 compliance: Adding new vehicle types to [MovingObject - Type]

### ISSUE THREAD

**Issue by FlorianMueller87** [OpenSimulationInterface/open-simulation-interface#638]
#### Describe the feature
ASAM OSI and ISO 23150 or AUTOSAR ADI have a common history. Unfortunately, the inner structure, the naming and the definitions of the standards are differentiated from each other. This makes the work of developers unnecessary complicated for mostly no technical reasons. All sides should strive to reduce inequality.

ASAM OSI need more entries for osi_objects – MovingObject – Type to be compatible with AUTOSAR ADI PotentiallyMovingObjectClassificationType.

#### Describe the solution you would like
Replace in osi_objects – MovingObject – Type TYPE_VEHICLE with TYPE_OTHER_VEHICLE and add the following entries after TYPE_ANIMAL: 
// Object is a Car.
//
TYPE_CAR = 5;

// Object is a heavy Truck.
//
TYPE_HEAVY_TRUCK = 6;

// Object is a Van.
//
TYPE_VAN = 7;

// Object is a Bus.
//
TYPE_BUS = 8;

// Object is a Trailer.
//
TYPE_TRAILER = 9;

// Object is a Semitrailer.
//
TYPE_SEMITRAILER = 10;

// Object is a Tram.
//
TYPE_TRAM = 11;

// Object is a Train.
//
TYPE_TRAIN = 12;

// Object is a Motorbike.
//
TYPE_MOTORBIKE = 13;

// Object is a Bicycle.
//
TYPE_BICYCLE = 14;

// Object is a Tricycle.
//

TYPE_TRICYCLE = 15;

// Object is a Wheelchair.
//
TYPE_WHEELCHAIR = 16;

#### Describe alternatives you have considered
TYPE_VEHICLE could also be replaced by another vehicle entry.

#### Describe the backwards compatibility
The adding of the elements will not lead to backward compatibility issues.

The changing of the name of TYPE_VEHICLE would lead to a backward compatibility issue. However, this would be detected by any compiler and could easily be change from the users.

#### Additional context
ISO23150:2021 A.76 Enumeration: Potentially moving object classification type – Example enumerators

@ThomasNaderBMW @jdsika @bytesnake

**Comment by pmai** [comment]
The MovingObject.type enum is the wrong place to handle vehicle sub-types, since the type only indicates whether the MovingObject is a vehicle, pedestrian or animal; vehicle sub-types are then handled at the MovingObject.VehicleClassification.type enum, which already contains all of the given sub-types (and more), with the exception of the tricycle.

As this is a shared part of both GroundTruth and SensorData, and mapping is trivially accomplished, this is not likely to change.

So if anything, a PR should be created to add an enum entry for tricycles to the MovingObject.VehicleClassification.type enum.

**Comment by FlorianMueller87** [comment]
Thank you, I will create an issue for adding tricycles. 

Close
