### ISSUE TITLE
Ground truth id repeated in DetectedItemHeader

### ISSUE THREAD

**Issue by jruebsam** [OpenSimulationInterface/open-simulation-interface#740]
Having a look at the DetectedItemHeader definition I realised that ground_truth_id  is defined as a repeated message.
Is this desired behavior, since e.g. vor a moving object only a single id  is defined ?

**Comment by thomassedlmayer** [comment]
I talked to Pierre about this and he told me that it most probably was intended to allow referencing multiple ground truth references to merge multiple ground truth objects into a single detected object. This may especially make sense for some stationary objects. This is just not stated properly in the documentation.

My first guess that this may have been a fix to the protobuf issue concerning empty numeric field was wrong since `ground_truth_id` is not a numeric field but is of type `Identifier`.
