### ISSUE TITLE
Travis CI (Unit and Smoke Tests)

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#8]
We should discuss the possibility to use the services in Github and integrate some tests in order to validate new versions. This might be a longer discussion.

**Comment by CarloVanDriestenBMW** [comment]
unit tests are complicated but it should compile

**Comment by CarloVanDriestenBMW** [comment]
@mbinna I think I allowed the access to "Travis CI", do you need more permissions or should I configure something so you can play around with it?

**Comment by mbinna** [comment]
@CarloVanDriestenBMW I cannot enable the repository on Travis CI, because I do not have admin access. Can you enable it? 
![screen shot 2017-02-06 at 20 39 26](https://cloud.githubusercontent.com/assets/161041/22663375/a2bab700-ecac-11e6-829e-113035907e49.png)

**Comment by CarloVanDriestenBMW** [comment]
@mbinna I think you can try again now :)

**Comment by mbinna** [comment]
Yes, Travis can access the repository. Thanks.

On Tue, 7 Feb 2017 at 09:12, Carlo van Driesten <notifications@github.com>
wrote:

@mbinna <https://github.com/mbinna> I think you can try again now :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenSimulationInterface/open-simulation-interface/issues/8#issuecomment-277929238>,
or mute the thread
