### ISSUE TITLE
OSI-Version mismatch possible because of being optional

### ISSUE THREAD

**Issue by JonathanSchmalhoferBMW** [OpenSimulationInterface/open-simulation-interface#92]
The Version is set as default value for the message **InterfaceVersion** within the **setup.py** script. All fields in that message are set to **optional**. Unfortunately, when creating a message for publishing and not explicitly setting the version values, we noticed, that the default values are not being used. So if Sender and Receiver have different OSI-Versions, by using default values, a mismatch will not be noticed. Our suggestion: The Sender should be **required** to fill the OSI-Version with his default values explicitly.

**Comment by JonathanSchmalhoferBMW** [comment]
I have to **correct** my statement above slightly:

Whenever an element in a message is labeled as **optional**, Google ProtocolBuffer will assume its' value as specified in the ***.proto**-File. This is wanted behaviour, as described in [here](https://developers.google.com/protocol-buffers/docs/proto#optional).

## Example
Assume the following example where an OSI-Sender and an OSI-Receiver exist. The Sender uses version 1 and the Receiver uses version 2. So this **should** result in a version mismatch warning or at even version mismatch error.

If the sender does **not** fill the optional field *Version*, it will be left empty when serializing. When the receiver then parses/deserialzes the Proto-Message, the not-set elements will be filled with default values. So on receiver-side, it will be filled with the default-value **2**. So the version mismatch **cannot be detected by a receiver**, when version fields are not set by the Sender.

I thus propose to make filling the OSI-Version a required element to be filled.

**Comment by pmai** [comment]
The only problem for now is, that changing the fields to be required from being optional technically makes the change non-backward compatible (i.e. code relying on the default behaviour will create protobufs that the new release code will reject due to missing fields), so that this would make our next release a v3.0.0 release.

The only alternative would be to leave the fields as optional, make the default values 0, and document that senders must fill out the values prior to sending. Receiving code can then treat messages with missing (i.e. 0) values as being from version 2.2.0 or prior...

@CarloVanDriestenBMW, @JonathanSchmalhoferBMW what would you prefer?

**Comment by CarloVanDriestenBMW** [comment]
Thinking about Proto3 I would go for the second option and leave out the "required" option?
